-- 고양이와 개는 몇 마리 있을까

SELECT ANIMAL_TYPE, count(ANIMAL_TYPE) AS count
from ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE

-- result:
-- ANIMAL_TYPE	count
-- Cat	15
-- Dog	85

-- 동명 동물 수 찾기
SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) >= 2
ORDER BY NAME
-- 정렬을 안해줬었음!

-- 연습문제
-- EMPLOYEES 테이블을 이용해 지점 별 총급여액이 얼마인지 조회하는 SQL문을 작성해주세요.
-- 단, 결과는 지점의 ID순으로 정렬되어야 합니다.
SELECT BRANCH_ID, SUM(SALARY) AS TOTAL
FROM EMPLOYEES
GROUP BY BRANCH_ID
ORDER BY BRANCH_ID ASC

-- 입양시각 구하기
-- 코드를 입력하세요
SELECT HOUR(DATETIME) AS HOUR , COUNT(HOUR(DATETIME))
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME)>=9 AND
    HOUR(DATETIME)<20
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)

-- 입양 시각 구하기 2
SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME)) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME)>=0 AND HOUR(DATETIME)<24
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)
-- fail: 이렇게 해서는 나머지 COUNT가 0인 시간이 안나옴!!

-- 새로운 변수 선언
SET @HOUR_LIST=-1; -- 변수 선언 및 초기화
SELECT
(@HOUR_LIST := @HOUR_LIST +1 ) AS HOUR,
(SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME)=@HOUR_LIST) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR_LIST <23;
-- ok (주의 : SET 문장 뒤에 세미콜론 붙여주기)
