-- https://programmers.co.kr/learn/courses/30/lessons/59035
-- 역순 정렬하기

SELECT NAME, DATETIME
from ANIMAL_INS
ORDER BY ANIMAL_ID DESC

-- 아픈 동물 찾기

SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'

--어린 동물 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION !='Aged'

-- 동물의 아이디와 이름
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

--여러 기준으로 정렬하기
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME ASC, DATETIME DESC -- 각각 적어주기

-- 상위 n개 레코드
-- 가장 먼저 들어온 강아지 이름 출력하기
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1